# Generated by Django 4.0.3 on 2022-03-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
