# Generated by Django 4.0.3 on 2022-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitems', '0002_alter_bookitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
