# Generated by Django 4.0.3 on 2022-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitems', '0003_bookitem_created_at_bookitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
