# Generated by Django 4.0.3 on 2022-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitems', '0004_alter_bookitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='aa',
            field=models.IntegerField(default=0),
        ),
    ]
