# Generated by Django 4.0.2 on 2022-02-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.category')),
            ],
        ),
    ]
