# Generated by Django 4.0.3 on 2022-03-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('totalAmount', models.FloatField(default=0)),
                ('totalQuantity', models.IntegerField(default=0)),
                ('customerId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LineBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(default=0)),
                ('bookItemBarCode', models.CharField(max_length=255)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carts.cart')),
            ],
        ),
    ]
