# Generated by Django 4.0.3 on 2022-03-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalQuantity',
        ),
    ]
