# Generated by Django 4.0.3 on 2022-03-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('middleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='persons.account')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='persons.address')),
                ('fullName', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='persons.fullname')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('point', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            bases=('persons.person',),
        ),
    ]
