# Generated by Django 4.0.3 on 2022-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_remove_person_xx'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='qqq',
            field=models.IntegerField(default=0),
        ),
    ]
