# Generated by Django 4.0.3 on 2022-03-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMoney', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.payment')),
                ('cashTendered', models.FloatField(default=0)),
            ],
            bases=('orders.payment',),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.payment')),
                ('number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
            bases=('orders.payment',),
        ),
        migrations.CreateModel(
            name='DigitalWallet',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.payment')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('orders.payment',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('customerId', models.IntegerField(default=0)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='carts.cart')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='orders.payment')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.shipment')),
            ],
        ),
    ]
