# Generated by Django 4.0.3 on 2022-03-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='xx',
            field=models.IntegerField(default=0),
        ),
    ]
