# Generated by Django 4.0.3 on 2022-03-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_xx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='xx',
        ),
    ]
